security: Abort on upstream key mismatch
Specifically, when the upstream signature matches the
image we can continue as normal. Otherwise this is dangerous and needs
manual intervention.

Signed-off-by: Venefilyn <freya@venefilyn.se>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -118,6 +118,23 @@ jobs:
         with:
           string: ${{ env.IMAGE_NAME }}
 
+      - name: Install Cosign
+        uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb # v3.8.2
+        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
+
+      # Verify the container image and if it fails, we just don't push this at all
+      # Something is up and we need to manually check
+      - name: Verify upstream container image
+        shell: bash
+        run: |
+          set -oue pipefail
+          echo "Get upstream image tag"
+          image=$(grep -i '^FROM.*:\S*' "./Containerfile" | awk '{print $2}')
+          echo "Using Cosign to verify image"
+          cosign verify \
+            --key ./build_files/ublue.pub \
+            "${image}"
+
       - name: Push To GHCR
         uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2
         if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
@@ -132,25 +149,8 @@ jobs:
           username: ${{ env.REGISTRY_USER }}
           password: ${{ env.REGISTRY_PASSWORD }}
 
-      # This section is optional and only needs to be enabled if you plan on distributing
-      # your project for others to consume. You will need to create a public and private key
-      # using Cosign and save the private key as a repository secret in Github for this workflow
-      # to consume. For more details, review the image signing section of the README.
-      - name: Install Cosign
-        uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb # v3.8.2
-        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
-
-      - name: Verify upstream container image
-        shell: bash
-        run: |
-          set -oue pipefail
-          echo "Get upstream image tag"
-          image=$(grep -i '^FROM.*:\S*' "./Containerfile" | awk '{print $2}')
-          echo "Using Cosign to verify image"
-          cosign verify \
-            --key https://raw.githubusercontent.com/ublue-os/main/main/cosign.pub \
-            "${image}"
-
+      # Signing container image so anyone and ourselves can easily verify its authenticity
+      # for future updates.
       - name: Sign container image
         if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
         run: |
